{
 "title": "JTI-OC-INTERFACES-telegraf",
 "tags": [
  "jti",
  "OC",
  "telegraf"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "device",
    "query": "SHOW TAG VALUES FROM \"/interfaces/\" with KEY=\"device\""
   },
   {
    "name": "if_name",
    "query": "SHOW TAG VALUES FROM \"/interfaces/\" with KEY=\"/interfaces/interface/@name\" WHERE device =~ /^$device/"
   },
   {
    "name": "ae_name",
    "query": "SHOW TAG VALUES FROM \"/interfaces/\" with KEY=\"/interfaces/interface/state/parent_ae_name\" WHERE device =~ /^$device/"
   }
  ]
 },
 "panels": [
  {
   "title": "Interfaces - INPUT pps (AE per member)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "alias": "[[tag_device]]-[[tag_/interfaces/interface/state/parent_ae_name]]-[[tag_/interfaces/interface/@name]]-IN",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(mean(\"/interfaces/interface/state/counters/in-pkts\"), 1s) FROM \"/interfaces/\" WHERE (\"device\" =~ /^$device$/ AND \"/interfaces/interface/state/parent_ae_name\" =~ /^$ae_name$/) AND $timeFilter GROUP BY time($__interval), \"device\", \"/interfaces/interface/state/parent_ae_name\", \"/interfaces/interface/@name\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Interfaces - INPUT - pps",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "alias": "[[tag_device]]-[[tag_/interfaces/interface/@name]]-IN",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(mean(\"/interfaces/interface/state/counters/in-pkts\"), 1s) FROM \"/interfaces/\" WHERE (\"device\" =~ /^$device$/ AND \"/interfaces/interface/@name\" =~ /^$if_name$/) AND $timeFilter GROUP BY time($__interval), \"device\", \"/interfaces/interface/@name\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Interfaces - OUTPUT - pps (AE per member)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "alias": "[[tag_device]]-[[tag_/interfaces/interface/state/parent_ae_name]]-[[tag_/interfaces/interface/@name]]-OUT",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "device" ], "type": "tag" },
      {
       "params": [
        "/interfaces/interface/state/parent_ae_name"
       ],
       "type": "tag"
      },
      { "params": [ "/interfaces/interface/@name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/interfaces/",
     "query": "SELECT non_negative_derivative(mean(\"/interfaces/interface/state/counters/out-pkts\"), 1s) FROM \"/interfaces/\" WHERE (\"device\" =~ /^$device$/ AND \"/interfaces/interface/state/parent_ae_name\" =~ /^$ae_name$/) AND $timeFilter GROUP BY time($__interval), \"device\", \"/interfaces/interface/state/parent_ae_name\", \"/interfaces/interface/@name\" fill(null)",
     "select": [
      [
       {
        "params": [
         "/interfaces/interface/state/counters/out-pkts"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=~", "value": "/^$device$/" },
      {
       "condition": "AND",
       "key": "/interfaces/interface/state/parent_ae_name",
       "operator": "=~",
       "value": "/^$ae_name$/"
      }
     ]
    }
   ]
  },
  {
   "title": "Interfaces - OUTPUT pps",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "alias": "[[tag_device]]-[[tag_/interfaces/interface/@name]]-out",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "device" ], "type": "tag" },
      { "params": [ "/interfaces/interface/@name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/interfaces/",
     "query": "SELECT non_negative_derivative(mean(\"/interfaces/interface/state/counters/out-pkts\"), 1s) FROM \"/interfaces/\" WHERE (\"device\" =~ /^$device$/ AND \"/interfaces/interface/@name\" =~ /^$if_name$/) AND $timeFilter GROUP BY time($__interval), \"device\", \"/interfaces/interface/@name\" fill(null)",
     "select": [
      [
       {
        "params": [
         "/interfaces/interface/state/counters/out-unicast-pkts"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=~", "value": "/^$device$/" },
      { "condition": "AND", "key": "/interfaces/interface/@name", "operator": "=~", "value": "/^$if_name$/" }
     ]
    }
   ]
  }
 ]
}