{
 "title": "Open NTI - SNMP",
 "tags": [
  "snmp",
  "telegraf"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "host_regex",
    "query": "SHOW TAG VALUES WITH KEY = \"hostname\""
   },
   {
    "name": "ifName",
    "query": "SHOW TAG VALUES WITH KEY = \"ifName\""
   }
  ]
 },
 "panels": [
  { "title": "SNMP traffic statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Traffic In/Out (bps)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "hostname" ], "type": "tag" },
      { "params": [ "ifName" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "interface_statistics",
     "query": "SELECT derivative(mean(\"ifHCInOctets\"), 1m) FROM \"interface_statistics\" WHERE \"hostname\" =~ /^$host_regex$/ AND \"ifName\" =~ /^$ifName$/ AND $timeFilter GROUP BY time(1m), \"hostname\", \"ifName\" fill(null)",
     "select": [
      [
       { "params": [ "ifHCInOctets" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1m" ], "type": "derivative" },
       { "params": [ "*8/60" ], "type": "math" },
       { "params": [ "in" ], "type": "alias" }
      ],
      [
       { "params": [ "ifHCOutOctets" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1m" ], "type": "derivative" },
       { "params": [ "*8/60" ], "type": "math" },
       { "params": [ "out" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$host_regex$/" },
      { "condition": "AND", "key": "ifName", "operator": "=~", "value": "/^$ifName$/" }
     ]
    }
   ]
  },
  {
   "title": "Traffic In/Out (Multicast pps)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "hostname" ], "type": "tag" },
      { "params": [ "ifName" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "interface_statistics",
     "query": "SELECT derivative(mean(\"ifHCInMulticastPkts\"), 1m) FROM \"interface_statistics\" WHERE \"hostname\" =~ /^$host_regex$/ AND \"ifName\" =~ /^$ifName$/ AND $timeFilter GROUP BY time(1m), \"hostname\", \"ifName\" fill(null)",
     "select": [
      [
       { "params": [ "ifHCInMulticastPkts" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1m" ], "type": "derivative" },
       { "params": [ "/60" ], "type": "math" },
       { "params": [ "in" ], "type": "alias" }
      ],
      [
       { "params": [ "ifHCOutMulticastPkts" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1m" ], "type": "derivative" },
       { "params": [ "/60" ], "type": "math" },
       { "params": [ "out" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$host_regex$/" },
      { "condition": "AND", "key": "ifName", "operator": "=~", "value": "/^$ifName$/" }
     ]
    }
   ]
  },
  {
   "title": "Traffic In/Out (Broadcast pps)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "hostname" ], "type": "tag" },
      { "params": [ "ifName" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "interface_statistics",
     "query": "SELECT derivative(mean(\"ifHCInBroadcastPkts\"), 1m), derivative(mean(\"ifHCOutBroadcastPkts\"), 1m) FROM \"interface_statistics\" WHERE \"hostname\" =~ /^$host_regex$/ AND \"ifName\" =~ /^$ifName$/ AND $timeFilter GROUP BY time(1m), \"hostname\", \"ifName\" fill(null)",
     "select": [
      [
       { "params": [ "ifHCInBroadcastPkts" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1m" ], "type": "derivative" },
       { "params": [ "/60" ], "type": "math" },
       { "params": [ "in" ], "type": "alias" }
      ],
      [
       { "params": [ "ifHCOutBroadcastPkts" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1m" ], "type": "derivative" },
       { "params": [ "/60" ], "type": "math" },
       { "params": [ "out" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$host_regex$/" },
      { "condition": "AND", "key": "ifName", "operator": "=~", "value": "/^$ifName$/" }
     ]
    }
   ]
  },
  {
   "title": "Traffic In/Out (Unicast pps)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "hostname" ], "type": "tag" },
      { "params": [ "ifName" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "interface_statistics",
     "query": "SELECT mean(\"value\") FROM \"measurement\" WHERE $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "ifHCInUcastPkts" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1m" ], "type": "derivative" },
       { "params": [ "/60" ], "type": "math" },
       { "params": [ "in" ], "type": "alias" }
      ],
      [
       { "params": [ "ifHCOutUcastPkts" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1m" ], "type": "derivative" },
       { "params": [ "/60" ], "type": "math" },
       { "params": [ "out" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$host_regex$/" },
      { "condition": "AND", "key": "ifName", "operator": "=~", "value": "/^$ifName$/" }
     ]
    }
   ]
  }
 ]
}