{
 "title": "JTI-UDP-INTERFACES-logstash",
 "tags": [
  "jti",
  "UDP",
  "Logstash"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "device",
    "query": "SHOW TAG VALUES FROM \"juniperNetworks.jnpr_interface_ext\" WITH KEY = \"device\""
   },
   {
    "name": "if_name",
    "query": "SHOW TAG VALUES FROM \"juniperNetworks.jnpr_interface_ext\" with KEY=\"interface_stats.if_name\" WHERE device =~ /^$device/"
   },
   {
    "name": "ae_name",
    "query": "SHOW TAG VALUES FROM \"juniperNetworks.jnpr_interface_ext\" with KEY=\"interface_stats.parent_ae_name\" WHERE device =~ /^$device/"
   },
   {
    "name": "queue",
    "query": "SHOW TAG VALUES FROM \"juniperNetworks.jnpr_interface_ext\" with KEY=\"interface_stats.egress_queue_info.queue_number\" WHERE device =~ /^$device/"
   }
  ]
 },
 "panels": [
  {
   "title": "Interfaces - INPUT pps (AE per member)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "alias": "[[tag_device]]-[[tag_interface_stats.parent_ae_name]]-[[tag_interface_stats.if_name]]-$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(mean(\"interface_stats.ingress_stats.if_pkts\"), 1s) AS \"IN\" FROM \"juniperNetworks.jnpr_interface_ext\" WHERE \"device\" =~ /^$device/ AND \"interface_stats.parent_ae_name\" =~ /^$ae_name$/ AND $timeFilter GROUP BY time($__interval), \"device\",\"interface_stats.parent_ae_name\",\"interface_stats.if_name\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Interfaces - INPUT - pps",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "alias": "[[tag_device]]-[[tag_interface_stats.if_name]]-$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(mean(\"interface_stats.ingress_stats.if_pkts\"), 1s) AS \"IN\" FROM \"juniperNetworks.jnpr_interface_ext\" WHERE \"device\" =~ /^$device/ AND \"interface_stats.if_name\" =~ /^$if_name$/ AND $timeFilter GROUP BY time($__interval), \"device\", \"interface_stats.if_name\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Interfaces - OUTPUT - pps (AE per member)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "alias": "[[tag_device]]-[[tag_interface_stats.parent_ae_name]]-[[tag_interface_stats.if_name]]-$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(mean(\"interface_stats.egress_stats.if_pkts\"), 1s) AS \"OUT\" FROM \"juniperNetworks.jnpr_interface_ext\" WHERE \"device\" =~ /^$device/ AND \"interface_stats.parent_ae_name\" =~ /^$ae_name$/ AND $timeFilter GROUP BY time($__interval), \"device\",\"interface_stats.parent_ae_name\",\"interface_stats.if_name\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Interfaces - OUTPUT pps",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "alias": "[[tag_device]]-[[tag_interface_stats.if_name]]-$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(mean(\"interface_stats.egress_stats.if_pkts\"), 1s) AS \"OUT\" FROM \"juniperNetworks.jnpr_interface_ext\" WHERE \"device\" =~ /^$device/ AND \"interface_stats.if_name\" =~ /^$if_name$/ AND $timeFilter GROUP BY time($__interval), \"device\", \"interface_stats.if_name\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}